# Azure DevOps pipeline to release a new version and deploy to production.

parameters:
  - name: 'DEV_DEPLOY'
    displayName: 'Deploy on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True

  - name: 'UAT_PROD_DEPLOY'
    displayName: 'Deploy on UAT then PROD environments'
    type: boolean
    default: False
    values:
      - False
      - True

# Triggers solo su tag
trigger:
  tags:
    include:
      - '*'  # Scatta su tutti i tag (generati dalla GitHub Action)

pr: none

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  vmImageNameDefault: 'ubuntu-latest'

pool:
  vmImage: '$(vmImageNameDefault)'

stages:

  - stage: build_dev_artifact
    dependsOn: []
    condition: eq(${{parameters.DEV_DEPLOY}}, true)
    displayName: 'Build DEV artifact'
    jobs:
      - job: job_build
        displayName: Build
        steps:
          # setups node by .nvmrc or .node-version file
          - template: local-templates/node-job-setup.yaml
          - template: local-templates/setup-env.yaml
            parameters:
              env: 'DEV'
              version: '$(Build.SourceBranchName):$(Build.SourceVersion)'
              vite_api_url: 'https://api-rtp.dev.cstar.pagopa.it/rtp'
              vite_auth_client_id: '1ec1f3f4-411b-4dc3-ad1c-68196af7e90c'

          - script: |
              npm run build
            displayName: 'npm build'

          - publish: dist
            artifact: Bundle

  - stage: deploy_dev
    displayName: 'Deploy to DEV'
    condition: succeeded()
    jobs:
      - job: job_deploy
        displayName: 'Deploy'
        steps:
          - checkout: none

          - download: current
            artifact: Bundle

          - task: AzureCLI@2
            displayName: 'Sync storage'
            inputs:
              azureSubscription: '$(DEV_AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob sync --container '$web' --account-name $(DEV_STORAGE_ACCOUNT_NAME) --source "$(Pipeline.Workspace)/Bundle"

          - task: AzureCLI@1
            displayName: 'Purge CDN endpoint'
            inputs:
              azureSubscription: '$(DEV_AZURE_SUBSCRIPTION)'
              scriptLocation: inlineScript
              inlineScript: |
                az cdn endpoint purge -g $(DEV_STORAGE_ACCOUNT_RG) -n $(DEV_CDN_ENDPOINT) --profile-name $(DEV_CDN_PROFILE) --content-paths "/*"

  - stage: build_uat_artifact
    dependsOn: []
    displayName: 'Build UAT artifact'
    condition:
      and(
        succeeded(),
        or(
          contains(variables['Build.SourceBranch'], 'refs/tags/'),
          contains(variables['Build.SourceBranch'], 'refs/heads/main')
        ),
        eq(${{parameters.UAT_PROD_DEPLOY}}, true)
      )
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: job_build
        displayName: Build
        steps:
          # setups node by .nvmrc or .node-version file
          - template: local-templates/node-job-setup.yaml
          - template: local-templates/setup-env.yaml
            parameters:
              env: 'UAT'
              version: '$(Build.SourceBranchName):$(Build.SourceVersion)'
              vite_api_url: 'https://api-rtp.dev.cstar.pagopa.it/rtp'
              vite_auth_client_id: '1ec1f3f4-411b-4dc3-ad1c-68196af7e90c'

          - script: |
              npm run build
            displayName: 'npm build'

          - publish: dist
            artifact: Bundle_UAT

  - stage: deploy_uat
    displayName: 'Deploy to UAT'
    dependsOn: [ 'build_uat_artifact' ]
    condition: succeeded()
    jobs:
      - job: job_deploy
        displayName: 'Deploy'
        steps:
          - checkout: none

          - download: current
            artifact: Bundle_UAT

          - task: AzureCLI@2
            displayName: 'Sync storage'
            inputs:
              azureSubscription: '$(UAT_AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob sync --container '$web' --account-name $(UAT_STORAGE_ACCOUNT_NAME) --source "$(Pipeline.Workspace)/Bundle_UAT"

          - task: AzureCLI@1
            displayName: 'Purge CDN endpoint'
            inputs:
              azureSubscription: '$(UAT_AZURE_SUBSCRIPTION)'
              scriptLocation: inlineScript
              inlineScript: |
                az cdn endpoint purge -g $(UAT_STORAGE_ACCOUNT_RG) -n $(UAT_CDN_ENDPOINT) --profile-name $(UAT_CDN_PROFILE) --content-paths "/*"

  - stage: build_prod_artifact
    displayName: 'Build PROD artifact'
    dependsOn: [ "deploy_uat" ]
    condition:
      and(
        or(
          contains(variables['Build.SourceBranch'], 'refs/tags/'),
          contains(variables['Build.SourceBranch'], 'refs/heads/main')
        ),
        eq(${{parameters.UAT_PROD_DEPLOY}}, true)
      )
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: job_build
        displayName: Build
        steps:
          # setups node by .nvmrc or .node-version file
          - template: local-templates/node-job-setup.yaml
          - template: local-templates/setup-env.yaml
            parameters:
              env: 'PROD'
              version: '$(Build.SourceBranchName):$(Build.SourceVersion)'
              vite_api_url: 'https://api-rtp.dev.cstar.pagopa.it/rtp'
              vite_auth_client_id: '1ec1f3f4-411b-4dc3-ad1c-68196af7e90c'

          - script: |
              npm run build
            displayName: 'npm build'

          - publish: dist
            artifact: Bundle_PROD

  - stage: prod_approve
    displayName: "Pending PROD deploy approval"
    dependsOn: ["build_prod_artifact"]
    jobs:
      - job: Deploy_Prod_WaitForApproval
        displayName: Wait for PROD approval
        pool: server
        timeoutInMinutes: 4320 # 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 4320 # 3 days
          inputs:
            onTimeout: 'skip'

  - stage: deploy_prod
    displayName: 'Deploy to PROD'
    dependsOn: [ 'prod_approve' ]
    condition: succeeded()
    jobs:
      - job: job_deploy
        displayName: 'Deploy'
        steps:
          - checkout: none

          - download: current
            artifact: Bundle_PROD

          - task: AzureCLI@2
            displayName: 'Sync storage'
            inputs:
              azureSubscription: '$(PROD_AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob sync --container '$web' --account-name $(PROD_STORAGE_ACCOUNT_NAME) --source "$(Pipeline.Workspace)/Bundle_PROD"

          - task: AzureCLI@1
            displayName: 'Purge CDN endpoint'
            inputs:
              azureSubscription: '$(PROD_AZURE_SUBSCRIPTION)'
              scriptLocation: inlineScript
              inlineScript: |
                az cdn endpoint purge -g $(PROD_STORAGE_ACCOUNT_RG) -n $(PROD_CDN_ENDPOINT) --profile-name $(PROD_CDN_PROFILE) --content-paths "/*"

