# Azure DevOps pipeline template used to build bundle.
parameters:
  - name: 'env'
    type: string
    default: ''

  - name: 'version'
    type: string
    default: ''

  - name: 'vite_api_url'
    type: string
    default: ''

  - name: 'vite_auth_client_id'
    type: string
    default: ''

steps:
- bash: |
    chmod +x env.sh
    env -i \
      RTP_FE_ENV=${{ parameters.env }} \
      RTP_FE_VERSION=${{ parameters.version }} \
      RTP_FE_VITE_API_URL=${{ parameters.vite_api_url }} \
      RTP_FE_VITE_AUTH_CLIENT_ID=${{ parameters.vite_auth_client_id }} \
      bash env.sh

  displayName: 'Populate environment file'
