/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const OkLazyImport = createFileRoute('/ok')()
const KoLazyImport = createFileRoute('/ko')()
const IdOkLazyImport = createFileRoute('/$id/ok')()

// Create/Update Routes

const OkLazyRoute = OkLazyImport.update({
  id: '/ok',
  path: '/ok',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ok.lazy').then((d) => d.Route))

const KoLazyRoute = KoLazyImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ko.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IdOkLazyRoute = IdOkLazyImport.update({
  id: '/$id/ok',
  path: '/$id/ok',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$id.ok.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoLazyImport
      parentRoute: typeof rootRoute
    }
    '/ok': {
      id: '/ok'
      path: '/ok'
      fullPath: '/ok'
      preLoaderRoute: typeof OkLazyImport
      parentRoute: typeof rootRoute
    }
    '/$id/ok': {
      id: '/$id/ok'
      path: '/$id/ok'
      fullPath: '/$id/ok'
      preLoaderRoute: typeof IdOkLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ko': typeof KoLazyRoute
  '/ok': typeof OkLazyRoute
  '/$id/ok': typeof IdOkLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ko': typeof KoLazyRoute
  '/ok': typeof OkLazyRoute
  '/$id/ok': typeof IdOkLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ko': typeof KoLazyRoute
  '/ok': typeof OkLazyRoute
  '/$id/ok': typeof IdOkLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/ko' | '/ok' | '/$id/ok'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/ko' | '/ok' | '/$id/ok'
  id: '__root__' | '/' | '/login' | '/ko' | '/ok' | '/$id/ok'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  KoLazyRoute: typeof KoLazyRoute
  OkLazyRoute: typeof OkLazyRoute
  IdOkLazyRoute: typeof IdOkLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  KoLazyRoute: KoLazyRoute,
  OkLazyRoute: OkLazyRoute,
  IdOkLazyRoute: IdOkLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/ko",
        "/ok",
        "/$id/ok"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/ko": {
      "filePath": "ko.lazy.tsx"
    },
    "/ok": {
      "filePath": "ok.lazy.tsx"
    },
    "/$id/ok": {
      "filePath": "$id.ok.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
